### ISSUE TITLE
Idea: Change 'master' to 'main' as default branch name

### ISSUE THREAD

**Issue by coliff** [h5bp/main.css#111]
[The default branch name for new repos in GitHub is now `main`](https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/). Many companies and major open source projects like Microsoft, IBM, Twitter, Red Hat, MySQL, the Linux kernel, and OpenBSD have changed their default branch to main. 

I think it'd be good to change our default branch to `main` too.

It's a particularly fitting name for this repo. :-)

It's easy to do and only takes a few minutes.

**Comment by roblarsen** [comment]
👍

**Comment by roblarsen** [comment]
(I'll be useful today!)

**Comment by coliff** [comment]
Nice!
https://github.com/h5bp/main.css/branches
