### ISSUE TITLE
.sr-only used on inputs causes huge problems in some scrolling setups

### ISSUE THREAD

**Issue by darsain** [h5bp/main.css#117]
The current `sr-only` utility class uses `position: absolute` with no coordinates as the main method to remove and stop element from affecting layout.

This doesn't play well with some scrolling setups combined with browsers new "feature" of scrolling to elements it thinks user is interacting with.

The problem is isolated and explained here (affects Chrome): https://output.jsbin.com/tamuvac

The fix would be to instead use:

```css
position: fixed;
left: 0;
top: 0;
```

**Comment by coliff** [comment]
Thanks for the demo and detailed write up in your JSBin demo. I'm not too sure about this yet though.

It looks to me like the demo is misusing the properties from the `sr-only` class. It's not intended to be applied to an interactive button - for example a checkbox or 'load more' button.

I can see and understand that using it in the way that you have in your demo can cause issues but I'm unsure if there is a real-world scenario where you'd want content hidden from screen-readers but that causes layout issues.

Out of interest, do you use Bootstrap at all? [They use the same class and CSS](https://getbootstrap.com/docs/4.6/utilities/screen-readers/) and haven't encountered any issues with it.

**Comment by darsain** [comment]
Is re-styling input elements in an accessible manner not a real world scenario?

Bootstrap is just using background images to restyle checkboxes, so they wouldn't run into this.

I personally don't care, I've fixed it on my end. Just thought you guys might be interested in making your sr-only class more robust and less issue prone.

For completeness, here is crbug fwiw https://crbug.com/1185149

**Comment by roblarsen** [comment]
@darsain Bootstrap actually share this same functionality as a helper class. @coliff wasn't referring to their internal use of it, but the fact that they ship a helper class that is implemented in the same way and they have even more eyeballs on their code than we do. We appreciate you bringing this to our attention.

**Comment by roblarsen** [comment]
I'm going with @coliff Thanks for the report!
