### ISSUE TITLE
Missing coma clip: rect(0 0 0 0);

### ISSUE THREAD

**Issue by borisov87** [h5bp/main.css#22]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (below))

clip: rect(0 0 0 0);
must be `clip: rect(0, 0, 0, 0);`
Because missing coma broke css validation in w3
https://github.com/h5bp/main.css/blob/b332512c56f1db4ec7b57e4ae3b8dfc10d778816/src/_helpers.css#L24

**Comment by roblarsen** [comment]
That was intentional, for a while. It's not valid now, so... PRs welcome! It's also a deprecated property, so there's that. It might be worth looking at again. 

https://github.com/h5bp/html5-boilerplate/pull/569 and https://github.com/h5bp/html5-boilerplate/issues/1030

**Comment by coliff** [comment]
Fixed this in a PR.

I agree that we should take a deeper look into this again and see if any further changes/improvements could be made.

I found this interesting Gist today:
https://gist.github.com/ffoodd/000b59f431e3e64e4ce1a24d5bb36034

Also for reference is Bootstrap's screenreader-only CSS
https://github.com/twbs/bootstrap/blob/master/scss/mixins/_screen-reader.scss

**Comment by roblarsen** [comment]
closed via #27
