### ISSUE TITLE
visuallyhidden > sr-only

### ISSUE THREAD

**Issue by coliff** [h5bp/main.css#25]
I'd like to propose that we rename the `visuallyhidden` class to `sr-only`.

- visuallyhidden isn't super clear exactly what it is for. The class is intended to be used for text which is only for screen readers so I think `sr-only` is more obvious and makes more sense
- The `sr-only` class is used by Bootstrap, the world's most popular CSS framework. It's sort of good to align with that.
- visuallyhidden isn't a word and is always flagged as a typo which bugs me :-)

**Comment by roblarsen** [comment]
💯 

I want to start to look at what we're doing here and update things for our current support matrix (e.g. #22)  This is a good first step.
