### ISSUE TITLE
Add a CHANGELOG.md

### ISSUE THREAD

**Issue by coliff** [h5bp/main.css#26]
I think it'd be good to add a CHANGELOG so folks who have downloaded the repo can see what has changed between versions, especially if there have been class name changes etc.

I think we should either add a `CHANGELOG.md` to the root of the project repo and list everything there like we do for HTML5 Boilerplate - or if not (to reduce duplication/effort) we could have an almost empty `CHANGELOG.md` with just include a link to the releases page on GitHub (https://github.com/h5bp/main.css/releases) which is less useful but better than nothing at all.

**Comment by roblarsen** [comment]
👍 for a proper `CHANGELOG.md`

**Comment by coliff** [comment]
oops, we have one already... I somehow missed that.

**Comment by roblarsen** [comment]
I never looked to see if we had one, so we're 2 for 2.
