### ISSUE TITLE
Update Supported Browsers Config & Docs

### ISSUE THREAD

**Issue by coliff** [h5bp/main.css#56]
I think we should modify the browserslist supported browsers to be:
> 0.5%, last 2 versions, Firefox ESR, not dead, IE11.

These are the browerlists defaults(https://github.com/browserslist/browserslist#queries) and includes a better range of defaults  - but with the addition of specifying IE11.

The best practises section is a good reference: https://github.com/browserslist/browserslist#best-practices

Note: Also need to update the list at: https://github.com/h5bp/main.css/blob/master/README.md#browser-support

**Comment by coliff** [comment]
You can get a full list of supported browsers at: https://browserl.ist/?q=defaults

**Comment by roblarsen** [comment]
@coliff This sounds good to me. I think that will be good to cut a release here and then we can move onto finishing up the html5-boilerplate release.
